export type CatalogueListing = {
  id: string
  slug: string
  landlordIndex: number
  title: string
  description: string
  county: 'Nairobi' | 'Kiambu' | 'Kajiado' | 'Machakos'
  area: string
  estate: string
  landmark: string
  latitude: number
  longitude: number
  distanceToCBD: number
  distanceToStage: number
  propertyType: 'SINGLE_ROOM' | 'BEDSITTER' | 'ONE_BEDROOM' | 'TWO_BEDROOM' | 'THREE_BEDROOM'
  buildingType: 'APARTMENT' | 'STANDALONE' | 'BUNGALOW'
  bedrooms: number
  bathrooms: number
  floorAreaSqM?: number
  monthlyRent: number
  deposit: number
  serviceCharge: number
  waterCharge: number
  garbageCharge: number
  waterType: 'BOREHOLE' | 'COUNCIL' | 'BOTH'
  electricityType: 'TOKEN' | 'POSTPAID'
  parking: boolean
  parkingSpaces: number
  petsAllowed: boolean
  familyFriendly: boolean
  bachelorFriendly: boolean
  gatedCommunity: boolean
  furnished: boolean
  amenities: string[]
  viewCount: number
}

const descriptions = {
  single: (place: string, water: string) => `Practical single room in ${place} with a shared bathroom and washing area. ${water}, prepaid electricity is available, and the route to the nearest matatu stage is well used throughout the day. The stated deposit and charges are the full move-in requirements.`,
  bedsitter: (place: string, water: string) => `Self-contained bedsitter in ${place} with a private bathroom, compact kitchenette and good natural light. ${water}, electricity uses tokens, and the building has a shared clothes-drying area. Shops and public transport are within walking distance.`,
  one: (place: string, water: string) => `One-bedroom rental in ${place} with a separate sitting room, practical kitchen cabinets and a private bathroom. ${water}, electricity is prepaid, and the compound has controlled access. Rent, deposit and recurring charges are shown separately.`,
  two: (place: string, water: string) => `Two-bedroom family flat in ${place} with one bathroom, a separate kitchen and a shared outdoor laundry area. ${water}, electricity is prepaid, and the building is within an easy walk of public transport and everyday shops.`,
  three: (place: string, water: string) => `Three-bedroom family home in ${place} with two bathrooms, a separate kitchen and a modest balcony or yard. ${water}, electricity is prepaid, and the compound provides controlled access and one parking space.`,
}

export const kenyanCatalogue: CatalogueListing[] = [
  { id: '10000000-0000-4000-8000-000000000001', slug: 'githurai-44-single-room', landlordIndex: 0, title: 'Single Room near Githurai 44 Stage', description: descriptions.single('Githurai 44', 'Council water is stored in shared tanks'), county: 'Nairobi', area: 'Githurai 44', estate: 'Progressive', landmark: 'Near Githurai 44 bus stage', latitude: -1.2012, longitude: 36.9129, distanceToCBD: 17, distanceToStage: 0.2, propertyType: 'SINGLE_ROOM', buildingType: 'APARTMENT', bedrooms: 0, bathrooms: 1, floorAreaSqM: 11, monthlyRent: 4500, deposit: 4500, serviceCharge: 0, waterCharge: 300, garbageCharge: 100, waterType: 'COUNCIL', electricityType: 'TOKEN', parking: false, parkingSpaces: 0, petsAllowed: false, familyFriendly: false, bachelorFriendly: true, gatedCommunity: false, furnished: false, amenities: ['Water Tank', 'Laundry Area'], viewCount: 218 },
  { id: '10000000-0000-4000-8000-000000000002', slug: 'mwiki-single-room', landlordIndex: 1, title: 'Single Room off Mwiki Road', description: descriptions.single('Mwiki', 'Borehole water is available daily'), county: 'Nairobi', area: 'Mwiki', estate: 'Njeri Road', landmark: 'Five minutes from Mwiki stage', latitude: -1.2243, longitude: 36.9488, distanceToCBD: 21, distanceToStage: 0.4, propertyType: 'SINGLE_ROOM', buildingType: 'APARTMENT', bedrooms: 0, bathrooms: 1, floorAreaSqM: 12, monthlyRent: 5000, deposit: 5000, serviceCharge: 0, waterCharge: 300, garbageCharge: 100, waterType: 'BOREHOLE', electricityType: 'TOKEN', parking: false, parkingSpaces: 0, petsAllowed: false, familyFriendly: false, bachelorFriendly: true, gatedCommunity: false, furnished: false, amenities: ['Water Tank', 'Security Gate'], viewCount: 245 },
  { id: '10000000-0000-4000-8000-000000000003', slug: 'githurai-45-bedsitter', landlordIndex: 2, title: 'Bedsitter in Githurai 45', description: descriptions.bedsitter('Githurai 45', 'Council water is backed up by rooftop tanks'), county: 'Kiambu', area: 'Githurai 45', estate: 'Mwihoko Road', landmark: 'Near Githurai market', latitude: -1.2001, longitude: 36.9262, distanceToCBD: 18, distanceToStage: 0.3, propertyType: 'BEDSITTER', buildingType: 'APARTMENT', bedrooms: 0, bathrooms: 1, floorAreaSqM: 19, monthlyRent: 6500, deposit: 6500, serviceCharge: 0, waterCharge: 300, garbageCharge: 100, waterType: 'COUNCIL', electricityType: 'TOKEN', parking: false, parkingSpaces: 0, petsAllowed: false, familyFriendly: false, bachelorFriendly: true, gatedCommunity: false, furnished: false, amenities: ['Water Tank', 'Laundry Area', 'WiFi Ready'], viewCount: 372 },
  { id: '10000000-0000-4000-8000-000000000004', slug: 'mwiki-bedsitter', landlordIndex: 3, title: 'Bedsitter near Mwiki Stage', description: descriptions.bedsitter('Mwiki', 'Borehole water is pumped to a shared storage tank'), county: 'Nairobi', area: 'Mwiki', estate: 'ACK Road', landmark: 'Near Mwiki stage', latitude: -1.2219, longitude: 36.9471, distanceToCBD: 21, distanceToStage: 0.2, propertyType: 'BEDSITTER', buildingType: 'APARTMENT', bedrooms: 0, bathrooms: 1, floorAreaSqM: 20, monthlyRent: 7000, deposit: 7000, serviceCharge: 0, waterCharge: 300, garbageCharge: 100, waterType: 'BOREHOLE', electricityType: 'TOKEN', parking: false, parkingSpaces: 0, petsAllowed: false, familyFriendly: false, bachelorFriendly: true, gatedCommunity: true, furnished: false, amenities: ['Water Tank', 'Security Gate', 'Laundry Area'], viewCount: 486 },
  { id: '10000000-0000-4000-8000-000000000005', slug: 'pipeline-single-room', landlordIndex: 4, title: 'Single Room in Pipeline', description: descriptions.single('Pipeline', 'Council water is rationed and stored in the building tanks'), county: 'Nairobi', area: 'Pipeline', estate: 'Plot 10', landmark: 'Near Pipeline stage', latitude: -1.3181, longitude: 36.8887, distanceToCBD: 12, distanceToStage: 0.3, propertyType: 'SINGLE_ROOM', buildingType: 'APARTMENT', bedrooms: 0, bathrooms: 1, floorAreaSqM: 10, monthlyRent: 6000, deposit: 6000, serviceCharge: 0, waterCharge: 400, garbageCharge: 100, waterType: 'COUNCIL', electricityType: 'TOKEN', parking: false, parkingSpaces: 0, petsAllowed: false, familyFriendly: false, bachelorFriendly: true, gatedCommunity: false, furnished: false, amenities: ['Water Tank', 'Laundry Area'], viewCount: 302 },
  { id: '10000000-0000-4000-8000-000000000006', slug: 'pipeline-bedsitter', landlordIndex: 5, title: 'Bedsitter off Outering Road', description: descriptions.bedsitter('Pipeline', 'Water is stored in ground and rooftop tanks for rationing days'), county: 'Nairobi', area: 'Pipeline', estate: 'Tassia Junction', landmark: 'Eight minutes from Outering Road', latitude: -1.3167, longitude: 36.8943, distanceToCBD: 12, distanceToStage: 0.6, propertyType: 'BEDSITTER', buildingType: 'APARTMENT', bedrooms: 0, bathrooms: 1, floorAreaSqM: 21, monthlyRent: 8500, deposit: 8500, serviceCharge: 0, waterCharge: 400, garbageCharge: 150, waterType: 'COUNCIL', electricityType: 'TOKEN', parking: false, parkingSpaces: 0, petsAllowed: false, familyFriendly: false, bachelorFriendly: true, gatedCommunity: true, furnished: false, amenities: ['Water Tank', 'Security Gate', 'WiFi Ready'], viewCount: 441 },
  { id: '10000000-0000-4000-8000-000000000007', slug: 'umoja-bedsitter', landlordIndex: 0, title: 'Bedsitter in Umoja Innercore', description: descriptions.bedsitter('Umoja Innercore', 'Council and borehole water are stored on site'), county: 'Nairobi', area: 'Umoja', estate: 'Innercore', landmark: 'Near Umoja market', latitude: -1.2798, longitude: 36.8947, distanceToCBD: 10, distanceToStage: 0.4, propertyType: 'BEDSITTER', buildingType: 'APARTMENT', bedrooms: 0, bathrooms: 1, floorAreaSqM: 22, monthlyRent: 9000, deposit: 9000, serviceCharge: 0, waterCharge: 300, garbageCharge: 150, waterType: 'BOTH', electricityType: 'TOKEN', parking: false, parkingSpaces: 0, petsAllowed: false, familyFriendly: false, bachelorFriendly: true, gatedCommunity: true, furnished: false, amenities: ['Water Tank', 'Security Gate', 'Laundry Area'], viewCount: 520 },
  { id: '10000000-0000-4000-8000-000000000008', slug: 'njiru-bedsitter', landlordIndex: 1, title: 'Bedsitter near Njiru Shopping Centre', description: descriptions.bedsitter('Njiru', 'Borehole water is included in the monthly water charge'), county: 'Nairobi', area: 'Njiru', estate: 'Chokaa', landmark: 'Near Njiru Shopping Centre', latitude: -1.2709, longitude: 36.9668, distanceToCBD: 18, distanceToStage: 0.5, propertyType: 'BEDSITTER', buildingType: 'APARTMENT', bedrooms: 0, bathrooms: 1, floorAreaSqM: 21, monthlyRent: 7500, deposit: 7500, serviceCharge: 0, waterCharge: 300, garbageCharge: 100, waterType: 'BOREHOLE', electricityType: 'TOKEN', parking: false, parkingSpaces: 0, petsAllowed: false, familyFriendly: false, bachelorFriendly: true, gatedCommunity: true, furnished: false, amenities: ['Water Tank', 'Security Gate'], viewCount: 277 },
  { id: '10000000-0000-4000-8000-000000000009', slug: 'kasarani-bedsitter', landlordIndex: 2, title: 'Bedsitter near Seasons Kasarani', description: descriptions.bedsitter('Kasarani', 'Council water has a rooftop tank backup'), county: 'Nairobi', area: 'Kasarani', estate: 'Seasons', landmark: 'Near Seasons stage', latitude: -1.2238, longitude: 36.9014, distanceToCBD: 16, distanceToStage: 0.3, propertyType: 'BEDSITTER', buildingType: 'APARTMENT', bedrooms: 0, bathrooms: 1, floorAreaSqM: 24, monthlyRent: 11000, deposit: 11000, serviceCharge: 0, waterCharge: 400, garbageCharge: 150, waterType: 'COUNCIL', electricityType: 'TOKEN', parking: false, parkingSpaces: 0, petsAllowed: false, familyFriendly: false, bachelorFriendly: true, gatedCommunity: true, furnished: false, amenities: ['Water Tank', 'CCTV', 'WiFi Ready'], viewCount: 593 },
  { id: '10000000-0000-4000-8000-000000000010', slug: 'zimmerman-bedsitter', landlordIndex: 3, title: 'Bedsitter off Kamiti Road', description: descriptions.bedsitter('Zimmerman', 'Borehole and council water are stored in shared tanks'), county: 'Nairobi', area: 'Zimmerman', estate: 'Canopy', landmark: 'Six minutes from Kamiti Road', latitude: -1.2108, longitude: 36.8904, distanceToCBD: 15, distanceToStage: 0.5, propertyType: 'BEDSITTER', buildingType: 'APARTMENT', bedrooms: 0, bathrooms: 1, floorAreaSqM: 23, monthlyRent: 10000, deposit: 10000, serviceCharge: 0, waterCharge: 400, garbageCharge: 150, waterType: 'BOTH', electricityType: 'TOKEN', parking: false, parkingSpaces: 0, petsAllowed: false, familyFriendly: false, bachelorFriendly: true, gatedCommunity: true, furnished: false, amenities: ['Water Tank', 'Security Gate', 'Laundry Area'], viewCount: 461 },
  { id: '10000000-0000-4000-8000-000000000011', slug: 'kahawa-west-bedsitter', landlordIndex: 4, title: 'Bedsitter in Kahawa West', description: descriptions.bedsitter('Kahawa West', 'Council water is backed by a large shared tank'), county: 'Nairobi', area: 'Kahawa West', estate: 'Station Road', landmark: 'Near Kahawa West market', latitude: -1.1815, longitude: 36.9051, distanceToCBD: 19, distanceToStage: 0.3, propertyType: 'BEDSITTER', buildingType: 'APARTMENT', bedrooms: 0, bathrooms: 1, floorAreaSqM: 22, monthlyRent: 9500, deposit: 9500, serviceCharge: 0, waterCharge: 350, garbageCharge: 150, waterType: 'COUNCIL', electricityType: 'TOKEN', parking: false, parkingSpaces: 0, petsAllowed: false, familyFriendly: false, bachelorFriendly: true, gatedCommunity: true, furnished: false, amenities: ['Water Tank', 'WiFi Ready', 'Laundry Area'], viewCount: 348 },
  { id: '10000000-0000-4000-8000-000000000012', slug: 'rongai-bedsitter', landlordIndex: 5, title: 'Bedsitter near Maasai Lodge Road', description: descriptions.bedsitter('Ongata Rongai', 'Borehole water is available throughout the week'), county: 'Kajiado', area: 'Ongata Rongai', estate: 'Maasai Lodge', landmark: 'Near Maasai Lodge stage', latitude: -1.3988, longitude: 36.7561, distanceToCBD: 20, distanceToStage: 0.4, propertyType: 'BEDSITTER', buildingType: 'APARTMENT', bedrooms: 0, bathrooms: 1, floorAreaSqM: 23, monthlyRent: 8000, deposit: 8000, serviceCharge: 0, waterCharge: 300, garbageCharge: 100, waterType: 'BOREHOLE', electricityType: 'TOKEN', parking: false, parkingSpaces: 0, petsAllowed: false, familyFriendly: false, bachelorFriendly: true, gatedCommunity: true, furnished: false, amenities: ['Water Tank', 'Security Gate', 'Laundry Area'], viewCount: 414 },
  { id: '10000000-0000-4000-8000-000000000013', slug: 'kitengela-bedsitter', landlordIndex: 0, title: 'Bedsitter near Kitengela EPZ', description: descriptions.bedsitter('Kitengela', 'Borehole water is stored in a shared rooftop tank'), county: 'Kajiado', area: 'Kitengela', estate: 'EPZ', landmark: 'Near EPZ stage', latitude: -1.4703, longitude: 36.9523, distanceToCBD: 32, distanceToStage: 0.5, propertyType: 'BEDSITTER', buildingType: 'APARTMENT', bedrooms: 0, bathrooms: 1, floorAreaSqM: 22, monthlyRent: 7500, deposit: 7500, serviceCharge: 0, waterCharge: 300, garbageCharge: 100, waterType: 'BOREHOLE', electricityType: 'TOKEN', parking: false, parkingSpaces: 0, petsAllowed: false, familyFriendly: false, bachelorFriendly: true, gatedCommunity: true, furnished: false, amenities: ['Water Tank', 'Security Gate'], viewCount: 389 },
  { id: '10000000-0000-4000-8000-000000000014', slug: 'ruiru-one-bedroom', landlordIndex: 1, title: '1 Bedroom Flat in Ruiru', description: descriptions.one('Ruiru', 'Borehole and council water are stored on site'), county: 'Kiambu', area: 'Ruiru', estate: 'Gatongora', landmark: 'Near Ruiru bypass stage', latitude: -1.1455, longitude: 36.9652, distanceToCBD: 25, distanceToStage: 0.6, propertyType: 'ONE_BEDROOM', buildingType: 'APARTMENT', bedrooms: 1, bathrooms: 1, floorAreaSqM: 38, monthlyRent: 13000, deposit: 13000, serviceCharge: 0, waterCharge: 400, garbageCharge: 150, waterType: 'BOTH', electricityType: 'TOKEN', parking: false, parkingSpaces: 0, petsAllowed: false, familyFriendly: true, bachelorFriendly: true, gatedCommunity: true, furnished: false, amenities: ['Water Tank', 'Security Gate', 'Laundry Area', 'WiFi Ready'], viewCount: 612 },
  { id: '10000000-0000-4000-8000-000000000015', slug: 'kikuyu-one-bedroom', landlordIndex: 2, title: '1 Bedroom Flat near Kikuyu Town', description: descriptions.one('Kikuyu', 'Council water is backed by storage tanks'), county: 'Kiambu', area: 'Kikuyu', estate: 'Thogoto', landmark: 'Near Thogoto stage', latitude: -1.2605, longitude: 36.6677, distanceToCBD: 23, distanceToStage: 0.5, propertyType: 'ONE_BEDROOM', buildingType: 'APARTMENT', bedrooms: 1, bathrooms: 1, floorAreaSqM: 40, monthlyRent: 14000, deposit: 14000, serviceCharge: 0, waterCharge: 400, garbageCharge: 150, waterType: 'COUNCIL', electricityType: 'TOKEN', parking: false, parkingSpaces: 0, petsAllowed: false, familyFriendly: true, bachelorFriendly: true, gatedCommunity: true, furnished: false, amenities: ['Water Tank', 'Security Gate', 'Laundry Area'], viewCount: 455 },
  { id: '10000000-0000-4000-8000-000000000016', slug: 'mwiki-one-bedroom', landlordIndex: 3, title: '1 Bedroom Flat on Mwiki Road', description: descriptions.one('Mwiki', 'Borehole water is pumped into shared storage tanks'), county: 'Nairobi', area: 'Mwiki', estate: 'Red Soil', landmark: 'Near Red Soil stage', latitude: -1.2145, longitude: 36.9576, distanceToCBD: 22, distanceToStage: 0.3, propertyType: 'ONE_BEDROOM', buildingType: 'APARTMENT', bedrooms: 1, bathrooms: 1, floorAreaSqM: 36, monthlyRent: 11000, deposit: 11000, serviceCharge: 0, waterCharge: 350, garbageCharge: 150, waterType: 'BOREHOLE', electricityType: 'TOKEN', parking: false, parkingSpaces: 0, petsAllowed: false, familyFriendly: true, bachelorFriendly: true, gatedCommunity: true, furnished: false, amenities: ['Water Tank', 'Security Gate', 'WiFi Ready'], viewCount: 684 },
  { id: '10000000-0000-4000-8000-000000000017', slug: 'umoja-one-bedroom', landlordIndex: 4, title: '1 Bedroom Flat in Umoja Innercore', description: descriptions.one('Umoja Innercore', 'Council and borehole water are stored in the compound'), county: 'Nairobi', area: 'Umoja', estate: 'Innercore', landmark: 'Near Moi Drive stage', latitude: -1.2803, longitude: 36.8963, distanceToCBD: 10, distanceToStage: 0.4, propertyType: 'ONE_BEDROOM', buildingType: 'APARTMENT', bedrooms: 1, bathrooms: 1, floorAreaSqM: 39, monthlyRent: 14000, deposit: 14000, serviceCharge: 0, waterCharge: 350, garbageCharge: 150, waterType: 'BOTH', electricityType: 'TOKEN', parking: false, parkingSpaces: 0, petsAllowed: false, familyFriendly: true, bachelorFriendly: true, gatedCommunity: true, furnished: false, amenities: ['Water Tank', 'Security Gate', 'Laundry Area'], viewCount: 701 },
  { id: '10000000-0000-4000-8000-000000000018', slug: 'pipeline-two-bedroom', landlordIndex: 5, title: '2 Bedroom Flat in Pipeline', description: descriptions.two('Pipeline', 'Council water is rationed and backed by large storage tanks'), county: 'Nairobi', area: 'Pipeline', estate: 'Stage Mpya', landmark: 'Near Pipeline Stage Mpya', latitude: -1.3192, longitude: 36.8921, distanceToCBD: 12, distanceToStage: 0.3, propertyType: 'TWO_BEDROOM', buildingType: 'APARTMENT', bedrooms: 2, bathrooms: 1, floorAreaSqM: 55, monthlyRent: 22000, deposit: 22000, serviceCharge: 0, waterCharge: 500, garbageCharge: 200, waterType: 'COUNCIL', electricityType: 'TOKEN', parking: false, parkingSpaces: 0, petsAllowed: false, familyFriendly: true, bachelorFriendly: true, gatedCommunity: true, furnished: false, amenities: ['Water Tank', 'Security Gate', 'Laundry Area', 'CCTV'], viewCount: 754 },
  { id: '10000000-0000-4000-8000-000000000019', slug: 'kahawa-wendani-two-bedroom', landlordIndex: 0, title: '2 Bedroom Flat in Kahawa Wendani', description: descriptions.two('Kahawa Wendani', 'Council and borehole water are stored on site'), county: 'Kiambu', area: 'Kahawa Wendani', estate: 'Near Magunas', landmark: 'Near Kahawa Wendani stage', latitude: -1.1864, longitude: 36.9273, distanceToCBD: 21, distanceToStage: 0.4, propertyType: 'TWO_BEDROOM', buildingType: 'APARTMENT', bedrooms: 2, bathrooms: 1, floorAreaSqM: 60, monthlyRent: 28000, deposit: 28000, serviceCharge: 1000, waterCharge: 500, garbageCharge: 200, waterType: 'BOTH', electricityType: 'TOKEN', parking: true, parkingSpaces: 1, petsAllowed: false, familyFriendly: true, bachelorFriendly: true, gatedCommunity: true, furnished: false, amenities: ['Water Tank', 'Security Guard', 'Laundry Area', 'CCTV', 'WiFi Ready'], viewCount: 538 },
  { id: '10000000-0000-4000-8000-000000000020', slug: 'kinoo-two-bedroom', landlordIndex: 1, title: '2 Bedroom Flat near Kinoo Stage', description: descriptions.two('Kinoo', 'Council water is backed by ground and rooftop tanks'), county: 'Kiambu', area: 'Kinoo', estate: 'Muthiga', landmark: 'Near Muthiga stage', latitude: -1.2572, longitude: 36.6956, distanceToCBD: 19, distanceToStage: 0.4, propertyType: 'TWO_BEDROOM', buildingType: 'APARTMENT', bedrooms: 2, bathrooms: 1, floorAreaSqM: 58, monthlyRent: 27500, deposit: 27500, serviceCharge: 1000, waterCharge: 500, garbageCharge: 200, waterType: 'COUNCIL', electricityType: 'TOKEN', parking: true, parkingSpaces: 1, petsAllowed: false, familyFriendly: true, bachelorFriendly: true, gatedCommunity: true, furnished: false, amenities: ['Water Tank', 'Security Guard', 'Laundry Area', 'CCTV'], viewCount: 492 },
  { id: '10000000-0000-4000-8000-000000000021', slug: 'ruaka-one-bedroom', landlordIndex: 2, title: '1 Bedroom Flat in Ruaka', description: descriptions.one('Ruaka', 'Borehole and council water are available with tank storage'), county: 'Kiambu', area: 'Ruaka', estate: 'Ndenderu Road', landmark: 'Near Ruaka town stage', latitude: -1.2047, longitude: 36.7768, distanceToCBD: 14, distanceToStage: 0.5, propertyType: 'ONE_BEDROOM', buildingType: 'APARTMENT', bedrooms: 1, bathrooms: 1, floorAreaSqM: 43, monthlyRent: 28000, deposit: 28000, serviceCharge: 1500, waterCharge: 500, garbageCharge: 200, waterType: 'BOTH', electricityType: 'TOKEN', parking: true, parkingSpaces: 1, petsAllowed: false, familyFriendly: true, bachelorFriendly: true, gatedCommunity: true, furnished: false, amenities: ['Water Tank', 'Security Guard', 'CCTV', 'WiFi Ready', 'Balcony'], viewCount: 573 },
  { id: '10000000-0000-4000-8000-000000000022', slug: 'syokimau-two-bedroom', landlordIndex: 3, title: '2 Bedroom Flat in Syokimau', description: descriptions.two('Syokimau', 'Borehole water is stored in the compound tanks'), county: 'Machakos', area: 'Syokimau', estate: 'Katani Road', landmark: 'Near Katani Road stage', latitude: -1.3614, longitude: 36.9385, distanceToCBD: 22, distanceToStage: 0.7, propertyType: 'TWO_BEDROOM', buildingType: 'APARTMENT', bedrooms: 2, bathrooms: 2, floorAreaSqM: 68, monthlyRent: 38000, deposit: 38000, serviceCharge: 1500, waterCharge: 500, garbageCharge: 200, waterType: 'BOREHOLE', electricityType: 'TOKEN', parking: true, parkingSpaces: 1, petsAllowed: false, familyFriendly: true, bachelorFriendly: true, gatedCommunity: true, furnished: false, amenities: ['Water Tank', 'Security Guard', 'CCTV', 'Balcony', 'Laundry Area'], viewCount: 465 },
  { id: '10000000-0000-4000-8000-000000000023', slug: 'athi-river-three-bedroom', landlordIndex: 4, title: '3 Bedroom Bungalow in Athi River', description: descriptions.three('Athi River', 'Borehole water is stored in a private tank'), county: 'Machakos', area: 'Athi River', estate: 'Makadara', landmark: 'Near Athi River town', latitude: -1.4564, longitude: 36.9824, distanceToCBD: 31, distanceToStage: 0.8, propertyType: 'THREE_BEDROOM', buildingType: 'BUNGALOW', bedrooms: 3, bathrooms: 2, floorAreaSqM: 92, monthlyRent: 45000, deposit: 45000, serviceCharge: 0, waterCharge: 500, garbageCharge: 200, waterType: 'BOREHOLE', electricityType: 'TOKEN', parking: true, parkingSpaces: 1, petsAllowed: true, familyFriendly: true, bachelorFriendly: false, gatedCommunity: true, furnished: false, amenities: ['Water Tank', 'Security Gate', 'Laundry Area', 'Private Compound'], viewCount: 421 },
  { id: '10000000-0000-4000-8000-000000000024', slug: 'kasarani-three-bedroom', landlordIndex: 5, title: '3 Bedroom Flat in Kasarani', description: descriptions.three('Kasarani', 'Council and borehole water are stored in the building tanks'), county: 'Nairobi', area: 'Kasarani', estate: 'Clay City', landmark: 'Near Clay City stage', latitude: -1.2198, longitude: 36.9088, distanceToCBD: 17, distanceToStage: 0.5, propertyType: 'THREE_BEDROOM', buildingType: 'APARTMENT', bedrooms: 3, bathrooms: 2, floorAreaSqM: 84, monthlyRent: 52000, deposit: 52000, serviceCharge: 2000, waterCharge: 500, garbageCharge: 300, waterType: 'BOTH', electricityType: 'TOKEN', parking: true, parkingSpaces: 1, petsAllowed: false, familyFriendly: true, bachelorFriendly: false, gatedCommunity: true, furnished: false, amenities: ['Water Tank', 'Security Guard', 'CCTV', 'Balcony', 'Laundry Area'], viewCount: 449 },
]

export const marketRentGuardrails: Record<string, readonly [number, number]> = {
  'Githurai 44:SINGLE_ROOM': [3500, 5500],
  'Mwiki:SINGLE_ROOM': [3500, 5500],
  'Githurai 45:BEDSITTER': [5000, 8000],
  'Mwiki:BEDSITTER': [5000, 8000],
  'Pipeline:SINGLE_ROOM': [4000, 7000],
  'Pipeline:BEDSITTER': [6000, 10000],
  'Pipeline:TWO_BEDROOM': [15000, 25000],
  'Umoja:BEDSITTER': [6000, 10000],
  'Umoja:ONE_BEDROOM': [10000, 15000],
  'Njiru:BEDSITTER': [6000, 10000],
  'Kasarani:BEDSITTER': [7000, 12000],
  'Kasarani:THREE_BEDROOM': [35000, 55000],
  'Zimmerman:BEDSITTER': [7000, 12000],
  'Kahawa West:BEDSITTER': [7000, 12000],
  'Ongata Rongai:BEDSITTER': [6000, 10000],
  'Kitengela:BEDSITTER': [6000, 10000],
  'Ruiru:ONE_BEDROOM': [10000, 18000],
  'Kikuyu:ONE_BEDROOM': [10000, 18000],
  'Mwiki:ONE_BEDROOM': [8000, 12000],
  'Kahawa Wendani:TWO_BEDROOM': [18000, 30000],
  'Kinoo:TWO_BEDROOM': [16000, 28000],
  'Ruaka:ONE_BEDROOM': [18000, 30000],
  'Syokimau:TWO_BEDROOM': [28000, 45000],
  'Athi River:THREE_BEDROOM': [35000, 55000],
}

export function listingFitsMarketGuardrail(listing: CatalogueListing) {
  const range = marketRentGuardrails[`${listing.area}:${listing.propertyType}`]
  return Boolean(range && listing.monthlyRent >= range[0] && listing.monthlyRent <= range[1])
}

export function demoPhotoPath(slug: string, index: number) {
  return `/images/demo-listings/${slug}-${index}.webp`
}
